<div style="color:black; border-radius: 5px; background-color:#E7E9EB;padding: 10px;">
    <p style="  padding: 5px;"><b>Finding 1 : </b>
    Importing Libraries
 </p>
</div>

<div style="color:black; border-radius: 5px; margin: 5px 0;font-family:'Source Sans Pro', sans-serif;">
 <h4 style="border-left: 4px solid #96D4D4; background: #D9EEE1; padding: 5px; font-family:'Source Sans Pro', sans-serif;">Code</h4>
</div>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

<div style="color:black; border-radius: 5px; background-color:#E7E9EB;padding: 10px;">
    <p style="  padding: 5px;"><b>Finding 2 : </b>
    Loading the Data
 </p>
</div>

<div style="color:black; border-radius: 5px; margin: 5px 0;font-family:'Source Sans Pro', sans-serif;">
 <h4 style="border-left: 4px solid #96D4D4; background: #D9EEE1; padding: 5px; font-family:'Source Sans Pro', sans-serif;">Code</h4>
</div>

In [2]:
dataset = pd.read_csv('CarPrice_Assignment.csv')

In [3]:
dataset.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [4]:
dataset.shape

(205, 26)

<div class="alert alert-block alert-info">
    <b>Explanation:</b>
   The data contains 205 rows and 26 columns, which means that it has 26 features
</div>

<div style="color:black; border-radius: 5px; background-color:#E7E9EB;padding: 10px;">
    <p style="  padding: 5px;"><b>Finding 3 : </b>
    Detemining the features in the dataset and the label(the price of the car here)
 </p>
</div>

<div style="color:black; border-radius: 5px; margin: 5px 0;font-family:'Source Sans Pro', sans-serif;">
 <h4 style="border-left: 4px solid #96D4D4; background: #D9EEE1; padding: 5px; font-family:'Source Sans Pro', sans-serif;">Code</h4>
</div>

In [5]:
x = dataset.iloc[: , :-1].values # this function takes the indexes of the column we want to extract from the dataset and the rows 
y = dataset.iloc[: , -1].values # will get the last column only

In [6]:
x.shape

(205, 25)

In [7]:
y.shape

(205,)

In [8]:
x

array([[1, 3, 'alfa-romero giulia', ..., 5000, 21, 27],
       [2, 3, 'alfa-romero stelvio', ..., 5000, 21, 27],
       [3, 1, 'alfa-romero Quadrifoglio', ..., 5000, 19, 26],
       ...,
       [203, -1, 'volvo 244dl', ..., 5500, 18, 23],
       [204, -1, 'volvo 246', ..., 4800, 26, 27],
       [205, -1, 'volvo 264gl', ..., 5400, 19, 25]], dtype=object)

<div style="color:black; border-radius: 5px; background-color:#E7E9EB;padding: 10px;">
    <p style="  padding: 5px;"><b>Finding 4 : </b>
    Detemining whether there are missing values or not
 </p>
</div>

<div style="color:black; border-radius: 5px; margin: 5px 0;font-family:'Source Sans Pro', sans-serif;">
 <h4 style="border-left: 4px solid #96D4D4; background: #D9EEE1; padding: 5px; font-family:'Source Sans Pro', sans-serif;">Code</h4>
</div>

In [9]:
dataset.isnull()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
201,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
202,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
203,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
204,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

<div class="alert alert-block alert-info">
    <b>Explanation:</b>
   It seems that there is no missing value in this data
</div>

<div style="color:black; border-radius: 5px; background-color:#E7E9EB;padding: 10px;">
    <p style="  padding: 5px;"><b>Finding 5 : </b>
        Deal with categorical data
 </p>
</div>

<div style="color:black; border-radius: 5px; margin: 5px 0;font-family:'Source Sans Pro', sans-serif;">
 <h4 style="border-left: 4px solid #96D4D4; background: #D9EEE1; padding: 5px; font-family:'Source Sans Pro', sans-serif;">Code</h4>
</div>

In [10]:
dataset.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [22]:
"""  , 3 , 4 , 5 , 6 , 7 , 8 , 14 , 15 , 17] """
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
data_encoded = pd.get_dummies(data=dataset , drop_first=True)

In [23]:
data_encoded

,car_ID,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,...,cylindernumber_three,cylindernumber_twelve,cylindernumber_two,fuelsystem_2bbl,fuelsystem_4bbl,fuelsystem_idi,fuelsystem_mfi,fuelsystem_mpfi,fuelsystem_spdi,fuelsystem_spfi
0,1,3,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,...,0,0,0,0,0,0,0,1,0,0
1,2,3,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,...,0,0,0,0,0,0,0,1,0,0
2,3,1,94.5,171.2,65.5,52.4,2823,152,2.68,3.47,...,0,0,0,0,0,0,0,1,0,0
3,4,2,99.8,176.6,66.2,54.3,2337,109,3.19,3.40,...,0,0,0,0,0,0,0,1,0,0
4,5,2,99.4,176.6,66.4,54.3,2824,136,3.19,3.40,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,109.1,188.8,68.9,55.5,2952,141,3.78,3.15,...,0,0,0,0,0,0,0,1,0,0
201,202,-1,109.1,188.8,68.8,55.5,3049,141,3.78,3.15,...,0,0,0,0,0,0,0,1,0,0
202,203,-1,109.1,188.8,68.9,55.5,3012,173,3.58,2.87,...,0,0,0,0,0,0,0,1,0,0
203,204,-1,109.1,188.8,68.9,55.5,3217,145,3.01,3.40,...,0,0,0,0,0,1,0,0,0,0
204,205,-1,109.1,188.8,68.9,55.5,3062,141,3.78,3.15,...,0,0,0,0,0,0,0,1,0,0

<div style="color:black; border-radius: 5px; background-color:#E7E9EB;padding: 10px;">
    <p style="  padding: 5px;"><b>Finding 6 : </b>
        Splitting the dataset
 </p>
</div>

<div style="color:black; border-radius: 5px; margin: 5px 0;font-family:'Source Sans Pro', sans-serif;">
 <h4 style="border-left: 4px solid #96D4D4; background: #D9EEE1; padding: 5px; font-family:'Source Sans Pro', sans-serif;">Code</h4>
</div>

In [24]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test  = train_test_split(data_encoded , y , test_size = 0.2 , random_state = 1)

<div style="color:black; border-radius: 5px; background-color:#E7E9EB;padding: 10px;">
    <p style="  padding: 5px;"><b>Finding 7 : </b>
        Building the model
 </p>
</div>

<div style="color:black; border-radius: 5px; margin: 5px 0;font-family:'Source Sans Pro', sans-serif;">
 <h4 style="border-left: 4px solid #96D4D4; background: #D9EEE1; padding: 5px; font-family:'Source Sans Pro', sans-serif;">Code</h4>
</div>

In [25]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train , y_train)

LinearRegression()

<div class="alert alert-block alert-info">
    <b>Explanation:</b>
       Fitting the model
</div>

<div style="color:black; border-radius: 5px; background-color:#E7E9EB;padding: 10px;">
    <p style="  padding: 5px;"><b>Finding 8 : </b>
       Make prediction
 </p>
</div>

<div style="color:black; border-radius: 5px; margin: 5px 0;font-family:'Source Sans Pro', sans-serif;">
 <h4 style="border-left: 4px solid #96D4D4; background: #D9EEE1; padding: 5px; font-family:'Source Sans Pro', sans-serif;">Code</h4>
</div>

In [26]:
y_pred = regressor.predict(X_test)

In [28]:
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred) , 1) , y_test.reshape(len(y_test) , 1)) , 1))

[[ 6669.   6669. ]
 [ 7999.   7999. ]
 [ 6338.   6338. ]
 [ 8916.5  8916.5]
 [10295.  10295. ]
 [25552.  25552. ]
 [ 8249.   8249. ]
 [ 5151.   5151. ]
 [ 6488.   6488. ]
 [10245.  10245. ]
 [17450.  17450. ]
 [17669.  17669. ]
 [16515.  16515. ]
 [ 9095.   9095. ]
 [12964.  12964. ]
 [11199.  11199. ]
 [ 9980.   9980. ]
 [ 6529.   6529. ]
 [18150.  18150. ]
 [11259.  11259. ]
 [ 8948.   8948. ]
 [ 6855.   6855. ]
 [16925.  16925. ]
 [ 7957.   7957. ]
 [ 9989.   9989. ]
 [ 7129.   7129. ]
 [14489.  14489. ]
 [ 7995.   7995. ]
 [ 6229.   6229. ]
 [ 7295.   7295. ]
 [ 8058.   8058. ]
 [ 8921.   8921. ]
 [41315.  41315. ]
 [ 9295.   9295. ]
 [17950.  17950. ]
 [ 7775.   7775. ]
 [ 8558.   8558. ]
 [32250.  32250. ]
 [15645.  15645. ]
 [22625.  22625. ]
 [ 5118.   5118. ]]

<div class="alert alert-block alert-info">
    <b>Explanation:</b>
       It seems that there is no diffrent between the actual data and the predicted one
</div>

<div style="color:black; border-radius: 5px; background-color:#E7E9EB;padding: 10px;">
    <p style="  padding: 5px;"><b>Finding 9 : </b>
      Getting the accuracy of the model
 </p>
</div>

<div style="color:black; border-radius: 5px; margin: 5px 0;font-family:'Source Sans Pro', sans-serif;">
 <h4 style="border-left: 4px solid #96D4D4; background: #D9EEE1; padding: 5px; font-family:'Source Sans Pro', sans-serif;">Code</h4>
</div>

In [29]:
# The mean squared error
print("Mean squared error: %.2f" % np.mean((regressor.predict(X_test) - y_test) ** 2))

Mean squared error: 0.00

In [30]:
# Explained variance score: 1 is perfect prediction
print('Variance score: %.2f' % regressor.score(X_test, y_test))

Variance score: 1.00